name: Basic Cicd pipeline - Github Hosted Runner
on:
 push:
jobs:
   clean:
     runs-on: ubuntu-latest
     steps:
       - name: checkout
         uses: actions/checkout@v4.2.2
       - uses: actions/checkout@v4
       - uses: actions/setup-java@v4
         with:
           distribution: 'temurin' # See 'Supported distributions' for available options
           java-version: '21'
       - name: clean job
         run:  mvn clean
   compile:
      runs-on: ubuntu-latest
      needs: clean 
      steps: 
       - name: checkout
         uses: actions/checkout@v4.2.2
       - uses: actions/setup-java@v4
         with:
           distribution: 'temurin' # See 'Supported distributions' for available options
           java-version: '21'
       - name: need compile
         run: mvn compile
   staticanalyis:
     needs: compile
     uses: Dicksonsrepo/register-app-maven/.github/workflows/static.yml@main
     with:
       projectkey: "register-app-maven"
       organisationkey: "Dicksonrepo"
     secrets:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
