name: static ananylis using sonarqube
on: [workflow_dispatch]
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2 
      - name: setup java
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: sonarqube
        run: 
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
           -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
           -Dsonar.host.url=https://sonarcloud.io \
           -Dsonar.organization=dicksonsrepo \
           -Dsonar.projectKey=Dicksonsrepo_register-app-maven
          
    
